### ISSUE TITLE
Plans for Cake 3.x

### ISSUE THREAD

**Issue by bobmulder** [p0lym0rphik/cakephp-metabehavior#4]
Hey,

You got plans for a metabehavior for Cake 3.x?

Thanks!

**Comment by p0lym0rphik** [comment]
Hi ! 
I am currently trying to modelize it. The first commit have to happen in the coming weeks.

**Comment by bobmulder** [comment]
Very cool! I am working on a try at https://github.com/cakemanager/cakephp-utils/blob/1.0/src/Model/Behavior/MetasBehavior.php. Maybe you are interested to join this behavior on my repo? The only problem I got is the query to receive the meta-data. Posting it is easy to implement...

**Comment by p0lym0rphik** [comment]
Hi ! Long time no talk ! Your proposition is always available ? If yes, i'm interested.

**Comment by bobmulder** [comment]
Hey man. Long time... I have tried many things locally but I can't get it work. The problem is on receiving the data. Saving the data is no problem. Do you have any suggestions? Feel free to join! We could discuss and program together on my utils plugin... When you are interested feel free to chat me at gitter. Greetz

**Comment by p0lym0rphik** [comment]
I find you on gitter and leave you a message. I close here ;) !
